### ISSUE TITLE
how to distinguish major group and minor group

### ISSUE THREAD

**Issue by bijiawei0818** [bakerjw/wavelet_gm_simulation#1]

**Comment by bakerjw** [comment]
Please read the following paper for an explanation, and then pose a more specific question if your question is still unresolved

https://web.stanford.edu/~bakerjw/Publications/Yamamoto_Baker_(2013)_Simulations,_BSSA.pdf

**Comment by bijiawei0818** [comment]
> Please read the following paper for an explanation, and then pose a more specific question if your question is still unresolved
> 
> https://web.stanford.edu/~bakerjw/Publications/Yamamoto_Baker_(2013)_Simulations,_BSSA.pdf

Thank you for your reply! However,I still have a doubt. In Fig.3, is the division of major and minor groups according to the following diagram?
![image](https://user-images.githubusercontent.com/53200909/117232095-17380d00-ae53-11eb-84bd-0e8a86c802ca.png)
**_Note:the red represents the major and the yellow means the minor_**
