### ISSUE TITLE
A doubt for this paper

### ISSUE THREAD

**Issue by bijiawei0818** [bakerjw/wavelet_gm_simulation#2]
Thank you for your reply! However,I still have a doubt. In Fig.3, is the division of major and minor groups according to the following diagram?
![image](https://user-images.githubusercontent.com/53200909/117467466-4bf8b100-af86-11eb-8dd8-00562e6792e3.png)
Note:the red represents the major and the yellow means the minor

**Comment by bakerjw** [comment]
The major coefficients are the large-amplitude coefficients (the darkly shaded ones) The mean and standard deviations indicated by the boundaries do not only apply to major coefficients.
